version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
  pre_build:
    commands:
      - rbenv install 3.2.0
      - gem install bundler -v 2.4.7
  build:
    commands:
      - bundle install
      - rails db:create RAILS_ENV=production
      - rails db:migrate RAILS_ENV=production
      - RAILS_ENV=production rake assets:precompile
artifacts:
  files:
    - public/assets/
    - Gemfile
    - Gemfile.lock
    - config/database.yml